

import React from 'react'
import { Roboto } from 'next/font/google'
import { Work_Sans } from 'next/font/google'


const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto', // to user in global css
})

const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-work-sans', // to user in global css
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by Akash",

  authors: [
    { name: "Akash", url: "https://google.com" },
    { name: "Rahul" }
  ],

  keywords: ["nextjs", "learn nextjs", "akash"],

  icons: {
    icon: "/file.svg",
  },

  openGraph: {
    title: "Create Next App",
    description: "Generated by Akash",
    url: "https://your-domain.com",
    siteName: "Next App",

    images: [
      {
        url: "https://your-domain.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "Next.js OG Image",
      },
    ],
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Create Next App",
    description: "Generated by Akash",
    images: ["https://your-domain.com/og-image.png"],
  },
};


function about() {
  return (
    <div className={`${roboto.variable} ${workSans.variable}`}>
      <h1 className={roboto.className}>Hii this is  admin about page </h1>

      <p>this is a paragraph</p>
      <p>this is a paragraph 2</p>

    <button className='bg-red-500 p-5' >click me </button>

    </div>
  )
}

export default about
